apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "httpfileserver.fullname" . }}
  labels:
    {{- include "httpfileserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "httpfileserver.fullname" . }}
  selector:
    matchLabels:
      {{- include "httpfileserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "httpfileserver.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "httpfileserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - --port={{ .Values.service.port }}
          - --root=/data
          - --user={{ .Values.username }}
          - --password={{ .Values.password }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.storage.volumeClaimTemplate }}
          volumeMounts:
          - mountPath: /data
            name: {{ include "httpfileserver.fullname" . }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- with .Values.storage.volumeClaimTemplate }}
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: {{ include "httpfileserver.fullname" $ }}
      labels:
      {{- include "httpfileserver.labels" $ | nindent 8 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

